# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
"""

!pip install xmltodict

import requests
import xmltodict
import pandas as pd

service_key = 'Xjrk7R6ncYtA8UHYXLRkSvKtzP89LzXulpjZjN4/Sn9dP+nynxQTX3qUhO9crXlvnn3dfaiFp6ukCral+R9fpA=='
url = 'http://apis.data.go.kr/1661000/EmergencyInformationService/getEmgPatientTransferInfo'

a = ['강남소방서', '강북소방서', '강동소방서', '강서소방서', '관악소방서', '광진소방서', '구로소방서', '도봉소방서', '노원소방서',
     '동대문소방서', '동작소방서', '마포소방서', '서대문소방서', '서초소방서', '성북소방서', '송파소방서', '양천소방서','영등포소방서',
     '용산소방서', '은평소방서', '종로소방서', '중랑소방서', '중부소방서', '성동소방서']
li = []

for i in a:
    params ={'serviceKey' : service_key, 'pageNo' : '1', 'numOfRows' : '150000', 'resultType' : 'xml', 'rsacGutFsttOgidNm' : i, 'stmtYm' : '202012' }
    response = requests.get(url, params=params)
    result = xmltodict.parse(response.text)

    for data in result['response']['body']['items']['item']:
        li.append([data['sidoHqOgidNm'], data['rsacGutFsttOgidNm'], data['stmtHh'], data['stmtYm'],  data['ptntSdtSeCdNm']])

df = pd.DataFrame(li)
df

!pip install --upgrade pandas-profiling

import pandas_profiling
df.profile_report()

df1 = df.rename(columns={0 : '본부', 1 : '소방서', 2 : '신고시간',  3 : '신고년월', 4 : '성별'})

index1 = df1[df1['본부'] != '서울소방재난본부'].index
print(len(index1))
df1 = df1.drop(index1)

df1

df1.describe()

df1.info()

import pickle
from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/ITStudy/package/df1_p.pk', 'wb') as f:
    pickle.dump(df1, f)

with open('/content/drive/MyDrive/ITStudy/package/df1_p.pk', 'rb') as f:
    df1 = pickle.load(f)

import plotly.express as px 
fig = px.histogram(df1, y='소방서')
fig.show()

import folium
import json

!pip install folium

geo_path = '/content/drive/MyDrive/package/seoulsigungu.geojson'
geo_str = json.load(open(geo_path, encoding = 'utf-8'))

from pandas.io.formats.style_render import DataFrame
maps = DataFrame()

maps.loc['영등포소방서', '위도'] = 37.52064
maps.loc['동대문소방서', '위도'] = 37.58379
maps.loc['용산소방서', '위도'] = 37.53111
maps.loc['광진소방서', '위도'] = 37.5437 
maps.loc['종로소방서', '위도'] = 37.5717
maps.loc['은평소방서', '위도'] = 37.61761
maps.loc['성북소방서', '위도'] = 37.60699
maps.loc['강남소방서', '위도'] = 37.49598
maps.loc['서초소방서', '위도'] = 37.4975
maps.loc['강서소방서', '위도'] = 37.56576
maps.loc['마포소방서', '위도'] = 37.56229
maps.loc['강동소방서', '위도'] = 37.54923
maps.loc['노원소방서', '위도'] = 37.65526
maps.loc['구로소방서', '위도'] = 37.4968
maps.loc['송파소방서', '위도'] = 37.50485
maps.loc['관악소방서', '위도'] = 37.4654
maps.loc['양천소방서', '위도'] = 37.5291
maps.loc['중랑소방서', '위도'] = 37.59538
maps.loc['동작소방서', '위도'] = 37.49651
maps.loc['서대문소방서', '위도'] = 37.58287
maps.loc['도봉소방서', '위도'] = 37.66586
maps.loc['강북소방서', '위도'] = 37.63268
maps.loc['중부소방서', '위도'] = 37.55794
maps.loc['성동소방서', '위도'] = 37.5528

maps.loc['영등포소방서', '경도'] = 126.9139239
maps.loc['동대문소방서', '경도'] = 127.0506879
maps.loc['용산소방서', '경도'] = 126.9809422
maps.loc['광진소방서', '경도'] = 127.0828
maps.loc['종로소방서', '경도'] = 126.9788
maps.loc['은평소방서', '경도'] = 126.9227127
maps.loc['성북소방서', '경도'] = 127.0232435
maps.loc['강남소방서', '경도'] = 127.0664088
maps.loc['서초소방서', '경도'] = 126.992
maps.loc['강서소방서', '경도'] = 126.8226558
maps.loc['마포소방서', '경도'] = 126.9087792
maps.loc['강동소방서', '경도'] = 127.1464401
maps.loc['노원소방서', '경도'] = 127.0771199
maps.loc['구로소방서', '경도'] = 126.8654
maps.loc['송파소방서', '경도'] = 127.1144708
maps.loc['관악소방서', '경도'] = 126.9438067
maps.loc['양천소방서', '경도'] = 126.8723
maps.loc['중랑소방서', '경도'] = 127.093966
maps.loc['동작소방서', '경도'] = 126.9443079
maps.loc['서대문소방서', '경도'] = 126.9356676
maps.loc['도봉소방서', '경도'] = 127.03179546
maps.loc['강북소방서', '경도'] = 127.038056
maps.loc['중부소방서', '경도'] = 126.9941953
maps.loc['성동소방서', '경도'] = 127.0385

maps['출동횟수'] = df1['소방서'].value_counts()

maps.rename( index={
        '영등포소방서': '영등포구',
        '동대문소방서': '동대문구',
        '용산소방서': '용산구',
        '광진소방서': '광진구',
        '종로소방서': '종로구',
        '은평소방서': '은평구',
        '성북소방서': '성북구',
        '강남소방서': '강남구',
        '서초소방서': '서초구',
        '강서소방서': '강서구',
        '마포소방서': '마포구',
        '강동소방서': '강동구',
        '노원소방서': '노원구',
        '구로소방서': '구로구',
        '송파소방서': '송파구',
        '관악소방서': '관악구',
        '양천소방서': '양천구',
        '중랑소방서': '중랑구',
        '동작소방서': '동작구',
        '서대문소방서': '서대문구',
        '도봉소방서': '도봉구',
        '강북소방서': '강북구',
        '중부소방서': '중구',
        '성동소방서': '성동구'}, inplace = True)

maps

map = folium.Map(
    location = [37.5502, 126.982],
    zoom_start = 10.5,
    tiles = 'cartodbpositron'
)

folium.GeoJson(
    geo_str,
    style_function = lambda x: {
			                    'color':'black',
    							'weight' :'1',
    							'fillOpacity':'0.1'}
).add_to(map)

for i in maps.index:
    folium.Marker([ maps.loc[i, '위도'],
                   maps.loc[i, '경도']], tooltip= i).add_to(map)

for i in maps.index:
    folium.CircleMarker([ maps.loc[i, '위도'],
                   maps.loc[i, '경도']], colot='skyblue', 
                   ).add_to(map)

folium.Choropleth(
    geo_data=geo_str,
    data=maps,
    columns=[maps.index, '출동횟수'],
    key_on='properties.SIG_KOR_NM',
    fill_color='OrRd').add_to(map)

map
